plugins {
    id "net.fabricmc.fabric-loom" version "1.17.17"
}

group = maven_group
version = mod_version

loom {
    accessWidenerPath = file("src/main/resources/economycraft.accesswidener")
}

base {
    archivesName = "${archives_name}-fabric-${mod_version}_${minecraft_version}"
}

tasks.withType(Jar).configureEach { archiveVersion = "" }

repositories {
    maven { url "https://maven.fabricmc.net/" }
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"
}

java {
    toolchain { languageVersion = JavaLanguageVersion.of(25) }
}
tasks.withType(JavaCompile).configureEach { options.release = 25 }

processResources {
    inputs.property "version", project.version
    inputs.property "minecraft_range", minecraft_range
    filesMatching("fabric.mod.json") {
        expand version: project.version, minecraft_range: minecraft_range
    }
}
