modLoader = "javafml"
loaderVersion = "[1,)"
license = "GPL-3.0"

[[mods]]
modId = "economycraft"
version = "${version}"
displayName = "Solo Economy"
authors = "Alborz"
logoFile = "assets/economycraft/logo.png"
description = '''
A solo survival shop and money system. Based on EconomyCraft by ReaZip.
'''

# ---- Minecraft:
[[dependencies.economycraft]]
modId = "minecraft"
type = "required"
versionRange = "[${mcLo},${mcHi})"
ordering = "NONE"
side = "BOTH"

# ---- NeoForge:
[[dependencies.economycraft]]
modId = "neoforge"
type = "required"
versionRange = "[${nfLo},${nfHi})"
ordering = "NONE"
side = "BOTH"

# ---- Architectury:
[[dependencies.economycraft]]
modId = "architectury"
type = "required"
versionRange = "[${archVer},)"
ordering = "NONE"
side = "BOTH"

# ---- Placeholder API NeoForge (optional, for mod-to-mod placeholder integration):
[[dependencies.economycraft]]
modId = "${placeholderModId}"
type = "optional"
versionRange = "[1,)"
ordering = "AFTER"
side = "BOTH"
